= Pyed Documentation
:sectnums:
:toc: left
:toclevels: 4
:encoding: utf-8
:lang: en
:numbered:
:experimental:
:xrefstyle: short
:source-language: python
:imagesdir:   docs/figures

== Introduction
This package is yet another tool to help generate graph using Python + https://www.yworks.com/products/yed[Yed].

.Other packages that exists (that took the best names):
* https://github.com/jamesscottbrown/pyyed[Pyyed] (My package is loosely based on this one)
* https://github.com/hadim/pygraphml[Pygraphml]
* https://networkx.org/documentation/stable/reference/readwrite/graphml.html[NetworkX]

My package focus on drawing simple graph to quickly visualise relations between informations. It's a crude subset of what graphs are capable of. My intent is to have a kind of https://inkscape.org/release[Inkscape], but for graph. https://www.yworks.com/products/yed[Yed] is that, but I don't want to add and draw manually dozen of nodes when trying to understand a datastructure or a code.

These pages are thought to provide quick documentation on what you can do with this package, especially the different types of nodes and the parameter and values available.

=== Why another package?
I wanted functionalities that do not exist in those packages. I wanted a way to create package with enhanced data visualisation, in particular node with list of information (GenericNode in Pyed), node with table of data (TableNode in Pyed) and custom nodes with any .svg file as a shape (SvgNode in Pyed).

=== Principle
This package will not create finalized graph on its own. You'll have to use https://www.yworks.com/products/yed[Yed] or another GUI that support .graphml to render the graph correctly. By default, node size is not adapted to its content, and all nodes are on top of eachother.



=== How to install
Without downloading the project, one can do:
[source]
----
pip install pyed
----

== Documentation
Documentation is available at:

https://pyed.readthedocs.io/en/latest/

To build the docs yourself, clone this repository and build the documentation with:
[source,bash]
----
pip install -e ".[docs]"
cd docs
make html
make latexpdf
----